# Generated by Django 3.1.5 on 2021-03-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddu_canteen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
